### ISSUE TITLE
init_banner.txt not available in linux dist

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#15]
Will create the folder with a base config file
Traceback (most recent call last):
  File "/usr/local/lib/platys.dist/platys.py", line 366, in <module>
  File "/usr/local/lib/platys.dist/click/core.py", line 829, in __call__
  File "/usr/local/lib/platys.dist/click/core.py", line 782, in main
  File "/usr/local/lib/platys.dist/click/core.py", line 1259, in invoke
  File "/usr/local/lib/platys.dist/click/core.py", line 1066, in invoke
  File "/usr/local/lib/platys.dist/click/core.py", line 610, in invoke
  File "/usr/local/lib/platys.dist/platys.py", line 212, in init
  File "/usr/local/lib/platys.dist/platys.py", line 359, in print_banner
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/platys.dist/init_banner.txt'

**Comment by ufasoli** [comment]
migrated to go and embedded
