### ISSUE TITLE
Errors on using Platys in WSL2 using Ubuntu 18.04

### ISSUE THREAD

**Issue by AronAWeller** [TrivadisPF/platys#22]
Using Platys on Windows Subsystem for Linux (WSL) specifically the actual WSL2 using Ubuntu 18.04.
The errors seems not to be bound to WSL, it is more a Python-Error. Could be in the dependencies.

Error-Output :
aron@TVD-AAWELLER:/mnt/c/Users/arona$ sudo curl -L "https://github.com/TrivadisPF/platys/releases/download/2.2.0/platys.tar.gz" -o /tmp/platys.tar.gz
[sudo] password for aron:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   1187      0 --:--:-- --:--:-- --:--:--  1187
100 14.6M  100 14.6M    0     0  4408k      0  0:00:03  0:00:03 --:--:-- 5244k
aron@TVD-AAWELLER:/mnt/c/Users/arona$ tar zvxf /tmp/platys.tar.gz
udo mv platys.dist/ /usr/local/lib/
sudo chown -R root:root /usr/local/lib/platys.dist/
sudo rm /tmp/platys.tar.gzplatys.dist/
platys.dist/_asyncio.so
platys.dist/_bisect.so
platys.dist/_blake2.so
....
aron@TVD-AAWELLER:/mnt/c/Users/arona$ sudo mv platys.dist/ /usr/local/lib/
aron@TVD-AAWELLER:/mnt/c/Users/arona$ sudo chown -R root:root /usr/local/lib/platys.dist/
aron@TVD-AAWELLER:/mnt/c/Users/arona$ sudo rm /tmp/platys.tar.gz
aron@TVD-AAWELLER:/mnt/c/Users/arona$ sudo ln -s /usr/local/lib/platys.dist/platys /usr/local/bin/platys
aron@TVD-AAWELLER:/mnt/c/Users/arona$ platys --version
platys - Trivadis Platform in a Box - v2.2.0
https://github.com/trivadispf/platys
Copyright (c) 2018-2020, Trivadis AG
aron@TVD-AAWELLER:/mnt/c/Users/arona$ mkdir -v platys-test
mkdir: created directory 'platys-test'
aron@TVD-AAWELLER:/mnt/c/Users/arona$ cd platys-test
aron@TVD-AAWELLER:/mnt/c/Users/arona/platys-test$ platys init -n platys-platform -sn trivadis/platys-modern-data-platform -sv 1.5.2 --structure flat
**Will create the folder with a base config file
Traceback (most recent call last):
  File "/usr/local/lib/platys.dist/urllib3/connectionpool.py", line 670, in urlopen
  File "/usr/local/lib/platys.dist/urllib3/connectionpool.py", line 392, in _make_request
  File "/usr/local/lib/platys.dist/http/client.py", line 1254, in request
  File "/usr/local/lib/platys.dist/http/client.py", line 1300, in _send_request
  File "/usr/local/lib/platys.dist/http/client.py", line 1249, in endheaders
  File "/usr/local/lib/platys.dist/http/client.py", line 1036, in _send_output
  File "/usr/local/lib/platys.dist/http/client.py", line 974, in send
  File "/usr/local/lib/platys.dist/docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/platys.dist/requests/adapters.py", line 439, in send
  File "/usr/local/lib/platys.dist/urllib3/connectionpool.py", line 724, in urlopen
  File "/usr/local/lib/platys.dist/urllib3/util/retry.py", line 403, in increment
  File "/usr/local/lib/platys.dist/urllib3/packages/six.py", line 734, in reraise
  File "/usr/local/lib/platys.dist/urllib3/connectionpool.py", line 670, in urlopen
  File "/usr/local/lib/platys.dist/urllib3/connectionpool.py", line 392, in _make_request
  File "/usr/local/lib/platys.dist/http/client.py", line 1254, in request
  File "/usr/local/lib/platys.dist/http/client.py", line 1300, in _send_request
  File "/usr/local/lib/platys.dist/http/client.py", line 1249, in endheaders
  File "/usr/local/lib/platys.dist/http/client.py", line 1036, in _send_output
  File "/usr/local/lib/platys.dist/http/client.py", line 974, in send
  File "/usr/local/lib/platys.dist/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/platys.dist/platys.py", line 366, in <module>
  File "/usr/local/lib/platys.dist/click/core.py", line 829, in __call__
  File "/usr/local/lib/platys.dist/click/core.py", line 782, in main
  File "/usr/local/lib/platys.dist/click/core.py", line 1259, in invoke
  File "/usr/local/lib/platys.dist/click/core.py", line 1066, in invoke
  File "/usr/local/lib/platys.dist/click/core.py", line 610, in invoke
  File "/usr/local/lib/platys.dist/platys.py", line 173, in init
  File "/usr/local/lib/platys.dist/platys.py", line 331, in pull_config
  File "/usr/local/lib/platys.dist/docker/models/containers.py", line 802, in run
  File "/usr/local/lib/platys.dist/docker/models/containers.py", line 861, in create
  File "/usr/local/lib/platys.dist/docker/api/container.py", line 430, in create_container
  File "/usr/local/lib/platys.dist/docker/api/container.py", line 440, in create_container_from_config
  File "/usr/local/lib/platys.dist/docker/api/client.py", line 289, in _post_json
  File "/usr/local/lib/platys.dist/docker/utils/decorators.py", line 46, in inner
  File "/usr/local/lib/platys.dist/docker/api/client.py", line 226, in _post
  File "/usr/local/lib/platys.dist/requests/sessions.py", line 578, in post
  File "/usr/local/lib/platys.dist/requests/sessions.py", line 530, in request
  File "/usr/local/lib/platys.dist/requests/sessions.py", line 643, in send
  File "/usr/local/lib/platys.dist/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))**

Proposal for fix : Seems that Python3 is needed for using Platys. A possible fix would be to use the shebang refering to python3. Alternative fix : Enable a Parameter for playts in which i can specify the Python-Version to use.

Please contact me if you got questions.

Regards,
Aron

**Comment by ufasoli** [comment]
This should normally be fixed after closing #20 migrated

**Comment by ufasoli** [comment]
This should normally be fixed after closing #20
